name: 每日新闻简报
on:
  schedule:
    # UTC时间 0点 = 北京时间早上8点，每天早上8点自动运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动点击触发测试

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TIAN_API_KEY: ${{ secrets.TIAN_API_KEY }}
      QYWX_WEBHOOK: ${{ secrets.QYWX_WEBHOOK }}
    steps:
      - uses: actions/checkout@v4
      # 安装ubuntu中文字体，解决中文方框乱码
      - name: 安装中文字体
        run: sudo apt-get install -y fonts-wqy-zenhei
      # 安装python依赖
      - name: 安装python依赖
        run: |
          pip install requests pillow
      - name: 执行脚本生成图片+推送微信
        run: python news.py
